create extension if not exists pgcrypto;
create extension if not exists btree_gist;

create table if not exists public.properties (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  description text,
  member_rate integer not null default 700 check (member_rate >= 0),
  non_member_rate integer not null default 1000 check (non_member_rate >= 0),
  contact_email text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  role text not null default 'admin' check (role in ('admin','hytteansvarlig','okonomi')),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.bookings (
  id uuid primary key default gen_random_uuid(),
  property_id uuid not null references public.properties(id) on delete cascade,
  kind text not null default 'rental' check (kind in ('rental','block')),
  date_from date not null,
  date_to date not null,
  customer_name text,
  customer_email text,
  customer_phone text,
  is_member boolean,
  nightly_rate integer check (nightly_rate >= 0),
  total_price integer check (total_price >= 0),
  status text not null default 'booked' check (status in ('booked','cancelled','completed')),
  public_reference text not null unique default upper(substr(encode(gen_random_bytes(8),'hex'),1,10)),
  phone_verified_at timestamptz,
  checked_at timestamptz,
  checked_by uuid references auth.users(id),
  paid_at timestamptz,
  paid_by uuid references auth.users(id),
  admin_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (date_to >= date_from),
  check (
    (kind = 'block') or
    (customer_name is not null and customer_email is not null and customer_phone is not null and is_member is not null and nightly_rate is not null and total_price is not null)
  )
);

alter table public.bookings
  drop constraint if exists bookings_no_overlap;

alter table public.bookings
  add constraint bookings_no_overlap
  exclude using gist (
    property_id with =,
    daterange(date_from, date_to + 1, '[)') with &&
  ) where (status in ('booked','completed'));

create table if not exists public.booking_events (
  id bigint generated by default as identity primary key,
  booking_id uuid not null references public.bookings(id) on delete cascade,
  event_type text not null,
  actor_user_id uuid references auth.users(id),
  note text,
  created_at timestamptz not null default now()
);

insert into public.properties (slug, name, description, member_rate, non_member_rate)
values ('vaffelhytta','Vaffelhytta','Foreningshytta',700,1000)
on conflict (slug) do nothing;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admin_users a
    where a.user_id = auth.uid() and a.active = true
  );
$$;

create or replace function public.get_public_availability(
  p_property_slug text,
  p_from date,
  p_to date
)
returns table(date_from date, date_to date)
language sql
stable
security definer
set search_path = public
as $$
  select b.date_from, b.date_to
  from public.bookings b
  join public.properties p on p.id = b.property_id
  where p.slug = p_property_slug
    and p.active = true
    and b.status in ('booked','completed')
    and daterange(b.date_from, b.date_to + 1, '[)') && daterange(p_from, p_to + 1, '[)')
  order by b.date_from;
$$;

create or replace function public.get_public_property(p_property_slug text)
returns table(
  slug text,
  name text,
  description text,
  member_rate integer,
  non_member_rate integer,
  contact_email text
)
language sql
stable
security definer
set search_path = public
as $$
  select p.slug, p.name, p.description, p.member_rate, p.non_member_rate, p.contact_email
  from public.properties p
  where p.slug = p_property_slug and p.active = true;
$$;

alter table public.properties enable row level security;
alter table public.admin_users enable row level security;
alter table public.bookings enable row level security;
alter table public.booking_events enable row level security;

create policy "admins_select_properties" on public.properties
for select to authenticated using (public.is_admin());

create policy "admins_update_properties" on public.properties
for update to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "admins_read_admin_users" on public.admin_users
for select to authenticated using (public.is_admin());

create policy "admins_read_bookings" on public.bookings
for select to authenticated using (public.is_admin());

create policy "admins_manage_bookings" on public.bookings
for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "admins_read_booking_events" on public.booking_events
for select to authenticated using (public.is_admin());

create policy "admins_add_booking_events" on public.booking_events
for insert to authenticated with check (public.is_admin());

grant execute on function public.get_public_availability(text,date,date) to anon, authenticated;
grant execute on function public.get_public_property(text) to anon, authenticated;

revoke all on public.bookings from anon;
revoke all on public.admin_users from anon;
revoke all on public.booking_events from anon;

comment on table public.bookings is 'Private booking data. Public calendar must use get_public_availability so customer details are never exposed.';
